# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        env:
          ZMIENNA: Ala ma kota
        run: |
          echo "$ZMIENNA"
          echo "$ZMIENNA" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.ZMIENNA }}"
        
  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
            echo "ZMIENNA_PROD='zmienna prod'" >> "$GITHUB_OUTPUT"
    outputs:
      prod_output: ${{ steps.sentence_maker.outputs.ZMIENNA_PROD }}

  consumer:
    needs: [producer]
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: |
          echo ${{ needs.producer.outputs.prod_output }}

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > trzy_plus_siedem.txt
      - name: zapisz_dodawanie
        uses: actions/upload-artifact@v4
        with:
          name: dodawanie trzy plus siedem
          path: trzy_plus_siedem.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: pobierz_dodawanie
        uses: actions/download-artifact@v4
        with:
          name: dodawanie trzy plus siedem
      - shell: bash
        run: |
          value=`cat trzy_plus_siedem.txt`
          echo $(expr $value \* 9) 
