on:
 workflow_dispatch:
env:
 cat_name: "Puszek"
 WORKFLOW_VAR: "Workflow variable"
jobs:
 display-variables:
   name: ${{ vars.ENVIRONMENT_VAR }}
   runs-on: ubuntu-latest
   env:
    JOB_VAR: "Job variable"
   steps:
   - name: Use variables 1
     env:
      STEP_VAR: "Step variable"
     run: |
      echo "Repository variable : $REPOSITORY_VAR"
      echo "Organization variable : $ORGANIZATION_VAR"
      echo "Environment variable : $ENVIRONMENT_VAR"
      echo "Ala ma kota o nazwie $cat_name"
      echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
      echo "Powinna być zmienna w scopie joba:$JOB_VAR"
      echo "Powinna być zmienna w scopie stepu:$STEP_VAR"
  
   - name: Use variables 2
     run: |
      echo "Ala ma kota o nazwie $cat_name"
      echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
      echo "Powinna być zmienna w scopie joba:$JOB_VAR"
      echo "NIE powinna być zmienna w scopie stepu:$STEP_VAR"
 display-variables2:
   runs-on: ubuntu-latest
   steps:
   - name: Use variables in display-variables2
     run: |
      echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
      echo "NIE powinna być zmienna w scopie joba:$JOB_VAR"
      echo "NIE powinna być zmienna w scopie stepu:$STEP_VAR"
 display-all-variables:
   runs-on: ubuntu-latest
   steps:
   - name: Show all env variables
     run: |
       env
