name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        description: logLevel
        options: 
        - info
        - warning
        - debug
        required: true
      environment:
        type: environment
        
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show log level
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
